version: "3.9"

services:
  db:
    image: postgres:latest
    hostname: db
    container_name: database
    environment:
      - POSTGRES_PASSWORD=nopassword
      - POSTGRES_USER=rinha_backend
      - POSTGRES_DB=production
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    healthcheck:
      test: "pg_isready -h db"
      interval: 3s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "200MB"

  service01: &service
    build:
      context: .
      target: server
      dockerfile: Dockerfile
    environment:
      - ENV=production
      - LOG_LEVEL=info
      - HTTP_ADDR=8000
      - POSTGRES_DSN=postgres://rinha_backend:nopassword@db:5432/production?sslmode=disable
    expose:
      - "8000:8000"
    hostname: service01
    container_name: service-01
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '128MB'

  service02:
    <<: *service
    hostname: service02
    container_name: service-02

  nginx:
    image: nginx:latest
    container_name: load-balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - service01
      - service02
    ports: 
      # Obrigatório expor/usar a porta 9999 no load balancer!
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "32MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1